nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ["*", "https://auparavant.fr","https://www.auparavant.fr"]
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
