nelmio_api_doc:
    documentation:

        info:
            title: Auparavant
            description: The Auparavant API allows you to retrieve memories, locality, name and type of place, additional photos and user data.
            version: 1.0.0

        paths:
            /api/login_check:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Login to obtain token to use secure routes.
                    requestBody:
                        description: Generate a new token
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Retrieves JWT token
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: user@user.fr
                        password:
                            type: string
                            default: password
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []    
    areas: # to filter documented areas
        default: 
            path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        
        # host_patterns: # document only routes with a host of the form api.*
        #     - ^api\.
    use_validation_groups: true

